MovieRama.Web/Controllers/MoviesController.cs
using System;
using System.Diagnostics;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MovieRama.Web.Domain;
using MovieRama.Web.Entities;
using MovieRama.Web.Models;

namespace MovieRama.Web.Controllers
{
    public class MoviesController : Controller
    {
        private readonly IMoviesRepository _moviesRepository;
        private string CurrentUserId => User.FindFirstValue(ClaimTypes.NameIdentifier);

        public MoviesController(IMoviesRepository moviesRepository)
        {
            _moviesRepository = moviesRepository;
        }

        // GET: Movies
        public async Task<IActionResult> Index(string sortOrder)
        {
            var movies = await _moviesRepository.GetMoviesOrderedByAsync(sortOrder);

            var moviesViewModels = movies.Select(movie =>
                new MovieViewModel(movie, movie.UserId == CurrentUserId, CurrentUserId));

            return View(moviesViewModels);
        }

        // GET: Movies/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Movies/Create
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Title", "Description")] MovieViewModel movieViewModel)
        {
            if (ModelState.IsValid)
            {
                var movie = new Movie
                {
                    Title = movieViewModel.Title,
                    Description = movieViewModel.Description,
                    DateOfPublication = DateTime.Now,
                    UserId = CurrentUserId
                };

                await _moviesRepository.InsertMovieAsync(movie);

                return RedirectToAction(nameof(Index));
            }

            return View(movieViewModel);
        }

        // GET: Movies/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int id)
        {
            var movie = await _moviesRepository.FindMovieByIdAsync(id);

            if (movie == null)
            {
                return NotFound();
            }

            if (movie.HasNotBeenCreatedByUser(CurrentUserId))
            {
                return Unauthorized();
            }

            return View(new MovieViewModel(movie));
        }

        // POST: Movies/Edit/5
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MovieId", "Title", "Description")]
            MovieViewModel movieViewModel)
        {
            if (id != movieViewModel.MovieId)
            {
                return NotFound();
            }

            var movie = await _moviesRepository.FindMovieByIdAsync(id);

            if (movie.HasNotBeenCreatedByUser(CurrentUserId))
            {
                return Unauthorized();
            }

            if (ModelState.IsValid)
            {
                movie.Title = movieViewModel.Title;
                movie.Description = movieViewModel.Description;

                await _moviesRepository.UpdateMovieAsync(movie);

                return RedirectToAction(nameof(Index));
            }

            return View(new MovieViewModel(movie));
        }

        [HttpGet]
        public async Task<IActionResult> PostedByUser(string id, string sortOrder)
        {
            if (string.IsNullOrWhiteSpace(id))
            {
                return NotFound();
            }

            var moviesPostedByUser = await _moviesRepository.GetMoviesPostedByUserOrderedByAsync(id, sortOrder);

            if (moviesPostedByUser.Count == 0)
            {
                return NotFound();
            }

            bool ShowEditLink(Movie movie) => User.Identity.IsAuthenticated
                                              && string.Equals(CurrentUserId, movie.UserId,
                                                  StringComparison.InvariantCultureIgnoreCase);

            var movieViewModels = moviesPostedByUser.Select(movie =>
                    new MovieViewModel(movie, showEditLink: ShowEditLink(movie), userId: CurrentUserId))
                .ToList();

            var moviesPostedByUserViewModel = new MoviesBostedByUserViewModel
            {
                MovieViewModels = movieViewModels,
                PostedByApplicationUser = movieViewModels.First().PostedByApplicationUser
            };

            return View(moviesPostedByUserViewModel);
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MovieRama.Web/Views/Movies/Create.cshtml
@model MovieViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create Movie</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" >
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
 
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MovieRama.Web/Views/Movies/Edit.cshtml
@model MovieViewModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit Movie</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MovieId" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control">
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MovieRama.Web/Views/Movies/Index.cshtml
@model IEnumerable<MovieViewModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Movies</h2>

<div class="well well-sm">
    Sort by:
    <a asp-action="Index" asp-route-sortOrder="likes">Likes</a> |
    <a asp-action="Index" asp-route-sortOrder="hates">Hates</a> |
    <a asp-action="Index" asp-route-sortOrder="date-posted">Date</a>
</div>

@if (User.Identity.IsAuthenticated)
{
    <p>
        <a asp-action="Create" class="btn btn-success"><span class="glyphicon glyphicon-plus-sign"></span> New Movie</a>
    </p>
}

@foreach (var movieViewModel in Model)
{
    @Html.Partial("_MoviePartial", movieViewModel)
}

@section Scripts{
    <script src="~/lib/signalr/dist/browser/signalr.js"></script>
    <script src="~/js/rating.js"></script>
}

MovieRama.Web/Views/Movies/PostedByUser.cshtml
@model MoviesBostedByUserViewModel

@{
    ViewData["Title"] = "Posted By User";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Movies Posted By: @Model.PostedByApplicationUser.FullName</h2>

<div class="well well-sm">
    Sort by:
    <a asp-action="PostedByUser" asp-route-sortOrder="likes">Likes</a> |
    <a asp-action="PostedByUser" asp-route-sortOrder="hates">Hates</a> |
    <a asp-action="PostedByUser" asp-route-sortOrder="date-posted">Date</a>
</div>

@if (User.Identity.IsAuthenticated)
{
    <p>
        <a asp-action="Create" class="btn btn-success"><span class="glyphicon glyphicon-plus-sign"></span> New Movie</a>
    </p>
}

@foreach (var movieViewModel in Model.MovieViewModels)
{
    @await Html.PartialAsync("_MoviePartial", movieViewModel)
}

@section Scripts{
    <script src="~/lib/signalr/dist/browser/signalr.js"></script>
    <script src="~/js/rating.js"></script>
}

MovieRama.Web/Views/Movies/_MoviePartial.cshtml
@model MovieViewModel

<div class="well well-lg" data-movieid="@Model.MovieId">
    <!-- When the movie has been posted by the current user, we should show an edit link-->
    @if (Model.ShowEditLink)
    {
        <a asp-action="Edit" asp-route-id="@Model.MovieId" class="btn btn-info btn-sm"><span class="glyphicon glyphicon-edit"></span> Edit Movie</a> 
    }
    <br />
    <h3>@Model.Title</h3>
    <br />
    @if (Model.PostedByApplicationUser != null)
    {
        var postedByApplicationUser = Model.PostedByApplicationUser;
        <div>
            <h4>Posted by: @Html.ActionLink(postedByApplicationUser.FullName, "PostedByUser", "Movies", new { id = postedByApplicationUser.Id })</h4>
            <span>@Model.DateOfPublication.ToString("dddd, dd MMMM yyyy HH:mm")</span>
        </div>
    }
    <br />
    @Model.Description
    <br />
    <br />
    @{
        // We should not allow for the user that has posted the movie (ShowEditLink -> true) to vote.
        // We should not allow for unauthenticate users to vote.
        var votingIsNotAllowed = !User.Identity.IsAuthenticated
                                 || Model.ShowEditLink;

    }

    @if (votingIsNotAllowed)
    {
        <button class="btn js-likeBtn" style="background-color: transparent;" disabled="disabled">
            <span class="glyphicon glyphicon-thumbs-up" style="color: green"> @Model.Likes</span>
        </button>
        <button class="btn js-hateBtn" style="background-color: transparent;" disabled="disabled">
            <span class="glyphicon glyphicon-thumbs-down" style="color: red"> @Model.Hates</span>
        </button>
    }
    else
    {
        if (Model.UserAlreadyLiked)
        {
            <button class="btn js-likeBtn" style="background-color: transparent;" disabled="disabled">
                <span class="glyphicon glyphicon-thumbs-up" style="color: green"> @Model.Likes</span>
            </button>
        }
        else
        {
            <button class="btn js-likeBtn" style="background-color: transparent;">
                <span class="glyphicon glyphicon-thumbs-up" style="color: green"> @Model.Likes</span>
            </button>
        }

        if (Model.UserAlreadyHated)
        {
            <button class="btn js-hateBtn" style="background-color: transparent;" disabled="disabled">
                <span class="glyphicon glyphicon-thumbs-down" style="color: red"> @Model.Hates</span>
            </button>
        }
        else
        {
            <button class="btn js-hateBtn" style="background-color: transparent;">
                <span class="glyphicon glyphicon-thumbs-down" style="color: red"> @Model.Hates</span>
            </button>
        }

        if (Model.UserAlreadyLiked || Model.UserAlreadyHated)
        {
            <button class="btn js-retractVote">Retract Vote</button>
        }
        else
        {
            <button class="btn js-retractVote" disabled="disabled">Retract Vote</button>
        }
    }
</div>